# .github/flat.yaml

# This section defines the steps to fetch data from each theater's website.
steps:
  - name: brattle
    http_url: https://brattlefilm.org/coming-soon/
    downloaded_filename: brattle.html

  - name: coolidge
    http_url: https://coolidge.org/
    downloaded_filename: coolidge.html

  - name: somerville
    http_url: https://www.somervilletheatre.com/schedule/
    downloaded_filename: somerville.html
    
# This section defines what to do after the files are downloaded.
postprocess:
  - uses: denoland/deno-run@v1
    with:
      script: postprocess.js
      entrypoint: |
        deno run --allow-read --allow-write postprocess.js brattle.html coolidge.html somerville.html schedule.json

# This section tells Flat Data to commit the resulting files.
commit:
  author_name: Movie Schedule Bot
  author_email: bot@example.com
  message: "Update movie schedules"
  # IMPORTANT: This pushes the final file to your live website branch.
  push_to_branch: gh-pages
  files:
    - schedule.json

